export const GET_POKEMON_LIST_REQUEST = 'GET_POKEMON_LIST_REQUEST';
export const GET_POKEMON_LIST_SUCCESS = 'GET_POKEMON_LIST_SUCCESS';
export const GET_POKEMON_LIST_FAILURE = 'GET_POKEMON_LIST_FAILURE';
export const GET_POKEMON_LIST_RESET = 'GET_POKEMON_LIST_RESET';

export const GET_POKEMON_REQUEST = 'GET_POKEMON_REQUEST';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAILURE = 'GET_POKEMON_FAILURE';
export const GET_POKEMON_RESET = 'GET_POKEMON_RESET';
